#+TITLE: Mattf's Homepage
#+AUTHOR: Matheus Fillipe
#+DATE: <2022-04-28 Thu>
#+DESCRIPTION: mattf.one
#+OPTIONS: num:nil ^:{}
#+INCLUDE: "./header.org"


* WELCOME
This is my personal homepage/blog build with emacs org-mode. I will mostly keep this as a place where I save things for myself that I could not put somewhere else. Also will use this page for doing some web experiments. Don't forget to check out the terminal and the fancy 3D mode on the left corner.

I like to code in general, try creating music, 3D art and games. I also have a high interest in many areas of physics and math which I will also try to include about when I have time.

This whole site is build from a CI pipeline that invokes emacs on a archlinux container building the static content. The source code for this whole blog can be found at [[https://github.com/matheusfillipe/myblog][this]] github repository. If you want to correct anything or ask anything [[https://docs.github.com/en/github-ae@latest/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests][PR's]] are welcome!


* Featured Posts
# LIST FEATURED BEGIN
- [[file:series/wave_propagation/1.org][Wave Propagation Part 1]]

- [[file:series/coding/1.org][Definitive solution for emacs's org-mode html exporting latex tikz]]

- [[file:series/coding/2.org][Adding a comment box with google firebase]]

- [[file:series/coding/3.org][IRC Sonic pi repl]]

# LIST FEATURED END



* Links

** Contact
- You might find me on this [[https://mangle.ga/irc][irc]].
- Or you can also [[mailto:matheusfillipeag@gmail.com][Mail me]].

** Projects
- [[https://aur.archlinux.org/packages?K=mattf&SeB=m][AUR Packages]]
- [[https://github.com/matheusfillipe/][Github]]
- [[https://gitlab.com/matheusfillipeag][Gitlab]]
- [[https://github.com/matheusfillipe/dotfiles][Dotfiles]]
- [[https://gitlab.com/matheusfillipeag/dotfiles][More Dotfiles]]
- [[https://github.com/matheusfillipe/ircbot][Regex IRC async Bot Framework]]

** Telegram Bots
- [[https://t.me/QuizTriviaBot][Trvia Quiz (multiple subjects using opentrivia API)]]
- [[https://t.me/dogs_collection_bot][Marco, the dog bot]]
- [[https://t.me/ircclientbot][Irc Client bot (A telegram->Irc bridge)]]



#+INCLUDE: "./footer.org" :minlevel 1
