#+TITLE: Mattf's Homepage
#+DESCRIPTION: mattf.tk
#+OPTIONS: num:nil ^:{}
#+INCLUDE: "./header.org"


* WELCOME
This is my personal website/blog build with emacs org-mode. The fancy background was made with [[https://threejs.org/][threejs]]. I like to code in general, create music, 3D art and games. I also have a high interest in many areas of physics and math which I will also write about here.

This whole site is built from a CI pipeline that invokes emacs on a archlinux container building the static content. The source code for this whole blog can be found at [[https://github.com/matheusfillipe/myblog][this]] github repository. If you want to correct anything or ask anything [[https://docs.github.com/en/github-ae@latest/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests][PR's]] are welcome!


* Featured Posts
[[file:series/wave_propagation/1.org][Wave Propagation Part 1]]


* Links

** Contact
- You might find me on this [[https://mangle.ga/irc][irc]].
- Or you can also [[mailto:matheusfillipeag@gmail.com][Mail me]].

** Projects
- [[https://aur.archlinux.org/packages?K=mattf&SeB=m][AUR Packages]]
- [[https://github.com/matheusfillipe/][Github]]
- [[https://gitlab.com/matheusfillipeag][Gitlab]]
- [[https://github.com/matheusfillipe/dotfiles][Dotfiles]]
- [[https://gitlab.com/matheusfillipeag/dotfiles][More Dotfiles]]
- [[https://github.com/matheusfillipe/ircbot][Regex IRC async Bot Framework]]

** Telegram Bots
- [[https://t.me/QuizTriviaBot][Trvia Quiz (multiple subjects using opentrivia API)]]
- [[https://t.me/dogs_collection_bot][Marco, the dog bot]]
- [[https://t.me/ircclientbot][Irc Client bot (A telegram->Irc bridge)]]



#+INCLUDE: "./footer.org" :minlevel 1
