version: 2.1

jobs:
  build:
    docker:
      - image: archlinux
    steps:
      - checkout
      - run: |
          yes | LC_ALL=en_US.UTF-8 pacman -Syu --noconfirm || true
          yes | LC_ALL=en_US.UTF-8 pacman -Sy --noconfirm emacs git nodejs npm tree wget || true
          npm install netlify-cli -g
          wget https://github.com/tdewolff/minify/releases/download/v2.11.1/minify_linux_amd64.tar.gz
          tar -xf minify_linux_amd64.tar.gz
          sed -i 's/^minify=.*/minify=1/' build.sh
          ./build.sh
          netlify deploy --site curious-squirrel-9f2b0c --auth $NETLIFY_ACCESS_TOKEN --prod --dir=html/

workflows:
  build-workflow:
    jobs:
      - build:
          filters:
            branches:
              only: master
