version: 2.1

jobs:
  build:
    docker:
      - image: archlinux
    steps:
      - checkout
      - run: |
          yes | pacman -Syu || true
          yes | pacman -Sy emacs git nodejs npm || true
          npm install netlify-cli -g
          ./build.sh
          netlify deploy --site curious-squirrel-9f2b0c --auth $NETLIFY_ACCESS_TOKEN --prod --dir=html/

workflows:
  build-workflow:
    jobs:
      - build:
          filters:
            branches:
              only: master
