version: 2.1

jobs:
  build:
    docker:
      - image: archlinux
    steps:
      - checkout
      - run: |
          yes | pacman -Sy emacs git || true
          ./build.sh

workflows:
  build-workflow:
    jobs:
      - build:
          filters:
            branches:
              only: master
